import turtle as t
t.bgcolor("#125364")
t.color("white")
t.penup()
t.goto(-400,0)
t.pendown()
t.color("green")
t.speed(0)
t.pensize(2)
t.showturtle()
for i in range (40):
    t.color("green")
    #t.fillcolor("green")
    #t.begin_fill()
    t.circle(100)
    #t.end_fill()
    t.left(5)
    t.color("yellow")
    #t.fillcolor("yellow")
    #t.begin_fill()
    t.circle(100)
    #t.end_fill()
    t.left(5)
t.right(40)
t.penup()
t.forward(400)
t.pendown()
for i in range (40):
    t.color("green")
    #t.fillcolor("green")
    #t.begin_fill()
    t.circle(100)
    #t.end_fill()
    t.left(5)
    t.color("red")
    #t.fillcolor("red")
    #t.begin_fill()
    t.circle(100)
    #t.end_fill()
    t.left(5)
t.right(40)
t.penup()
t.forward(400)
t.pendown()
for i in range (40):
    t.color("green")
    #t.fillcolor("green")
    #t.begin_fill()
    t.circle(100)
    #t.end_fill()
    t.left(5)
    t.color("blue")
    #t.fillcolor("blue")
    #t.begin_fill()
    t.circle(100)
    #t.end_fill()
    t.left(5)


    
